shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^static/img/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^welcome', views.welcome, name='welcome'),

    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^change_password$', views.change_password, name='change_password'),
    url(r'^forget_password$', views.forget_password, name='forget_password'),
    url(r'^logout$', views.logout, name='logout'),

    # url(r'^edit', views.edit, name='edit'),

    # url(r'^add', views.add, name='add'),

    url(r'^list$', views.goods_list, name='list'),
    url(r'^good/(?P<number>\d+)$', views.good_page, name='good_page'),
    url(r'^delete_good/(?P<number>\d+)/$', views.delete_good, name='delete_good'),

    # url(r'^add/$', views.add),
    # url(r'do_add/$', views.do_add),

    url(r'^edit$', views.edit_good, name='edit'),
    url(r're_edit/(?P<number>\d+)/$', views.re_edit, name='re_edit'),

    url(r'upload/$', views.upload, name='upload_img'),
    # url(r'^static/img/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^create_good$', views.create_good, name='create_good'),

    url(r'^add_to_car/(?P<number>\d+)/$', views.add_to_car, name='add_to_car'),
    url(r'^delete_from_car/(?P<number>\d+)/$', views.delete_from_car, name='delete_from_car'),
    url(r'^my_car$', views.car_page, name='my_car'),
    url(r'^car_increase_amount/(?P<number>\d+)/$', views.car_increase_amount, name='car_increase_amount'),
    url(r'^car_reduce_amount/(?P<number>\d+)/$', views.car_reduce_amount, name='car_reduce_amount'),

    url(r'^buy$', views.buy, name='buy'),
    url(r'^pay$', views.pay, name='pay'),

    url(r'^buyer$', views.show_buyer_list, name='buyer_list'),
    url(r'^seller$', views.show_seller_list, name='seller_list'),

    url(r'^finish_list', views.finish_list, name='finish_list'),
    url(r'^my_goods$', views.show_my_goods, name='my_goods'),
    url(r'^put_on/(?P<number>\d+)/$', views.put_on, name='put_on'),
    url(r'^put_off/(?P<number>\d+)/$', views.put_off, name='put_off'),
    url(r'^to_commit$', views.turn_to_commit, name='turn_to_commit'),
    url(r'^commit$', views.commit, name='commit'),
    url(r'^search$', views.search, name='search'),

    url(r'$', views.jump_to_none),
]


shoponline/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin', admin.site.urls),

    url(r'^captcha/', include('captcha.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'', include('shop.urls', namespace='shop')),
]

templates/BuyerList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户帐单</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    ----------------------------------------------------------------------------------------<br/>
    {% for foo in all_list %}
        订单号：{{ foo.detail_list.number }}<br/>
        卖家：{{ foo.detail_list.seller }}<br/>
        商品名：{{ foo.good.name }}<br/>
        <a href="{% url 'shop:good_page' foo.good.number %}" class="btn btn-primary">商品详情</a>
        <form action="{% url 'shop:turn_to_commit' %}" method="POST">
        {% csrf_token %}
            <input type="text" value="{{ foo.detail_list.number }}" name="list_number" hidden>
            <input type="text" value="{{ foo.good.number }}" name="good_number" hidden>
        订单状态：{{ foo.list_situation }}
        {% if foo.detail_list.status == 2 %}
            <input type="submit" value="评论">
        {% endif %}

        </form>

        <br/>
        {{ foo.good.image|safe }}<br/>
        ￥{{ foo.good.price }} × {{ foo.detail_list.amount }}个 = ￥{{ foo.one_total }}<br/>
        ----------------------------------------------------------------------------------------<br/>
    {% endfor %}
</body>
</html>

templates/CommitPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    <form action="{% url 'shop:commit' %}" method="POST">
    {% csrf_token %}
        <input type="text" value="{{ list_number }}" name="list_number" hidden>
        <input type="text" value="{{ good_number }}" name="good_number" hidden>

        商品名：{{ good.name }}<br/>
        卖家：{{ good.seller.name }}<br/>
        {{ good.image|safe }}<br/>
        价格：￥{{ good.price }}<br/>

        {% for foo in form %}
            {{ foo.label }}:{{ foo }}<br/>
        {% endfor %}
        <input type="submit" value="提交">
        <br/>{{ result }}
    </form>
</body>
</html>

templates/DetailList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详单</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    <form action="{% url 'shop:pay' %}" method="POST">
    {% csrf_token %}
        订单号：<p>{{ number }}</p><br/>
    <input type="text" value="{{ number }}" name="number" hidden>
    {% for foo in good_in_detail_list %}
        商品名：{{ foo.good.name }}<br/>
        价格：￥{{ foo.good.price }}<br/>
        {{ foo.good.image|safe }}<br/>
        数量：{{ foo.amount }}<br/><br/>
    {% endfor %}
    <h3>总价：￥{{ total_money }}</h3>
    {% if user.fund >= total_money %}
        <input type="submit" value="购买">
        {% else %}
        <input type="button" value="余额不足无法购买">
    {% endif %}

    </form>
</body>
</html>

templates/EditGood.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js"></script>
    {#    利用jquery来完成form上传等#}
    <script src="http://tinymce.cachefly.net/4.3/tinymce.min.js"></script>
    <script>
        tinymce.init({

            selector: '#my_editor',

            plugins: ["image", "code"],

            file_browser_callback: function (field_name, url, type, win) {

                if (type == 'image') $('#my_form input').click();

            }

        });
    </script>

    <title>商品编辑</title>

</head>

<body>
<a href="{% url 'shop:welcome' %}">首页</a><br/>
    <h2>{{ result }}</h2><br/><br/>
<form action="{% url 'shop:create_good' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <p hidden>商品编号<input type="text" name="number" value="{{ good.number }}"></p>

    商品名：<input type="text" name="name" value="{{ good.name }}"><br/>
    价格：<input type="text" name="price" value="{{ good.price }}"><br/>
    库存：<input type="text" name="amount" value="{{ good.amount }}"><br/>
    商品头像：<input type="file" name="img" value="{{ good.image }}"><br/>
    介绍：

    <textarea id="my_editor" rows="25" name="description">{{ good.description|safe }}</textarea>

    <br/>{{ form.lable }}{{ form }}<br/>
    <input type="submit">
</form>

<iframe id="form_target" name="form_target" style="display:none"></iframe>

<form id="my_form" action="{% url 'shop:upload_img' %}" target="form_target" method="post" enctype="multipart/form-data"
      style="width:0px;height:0;overflow:hidden">
    <input name="image" type="file" onchange="$('#my_form').submit();this.value='';">
</form>

</body>

</html>

templates/GoodsList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商品列表</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    <form action="{% url 'shop:search' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="keywords">
        <input type="submit" value="搜索">
    </form>

    <form action="{% url 'shop:list' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="按价格 升序" name="order">
        <input type="submit" value="按价格 降序" name="order">
        <input type="submit" value="按时间 升序" name="order">
        <input type="submit" value="按时间 降序" name="order">
    </form>
    <form action="{% url 'shop:list' %}">
        {% for foo in goods %}
            ---------------------------------------------------------------------------
            <br/>
        商品编码：{{ foo.number }}<br/>
        商品名：{{ foo.name }}<br/>
        价格：￥{{ foo.price }}<br/>
        头像：{{ foo.image|safe }}
        <a href="{% url 'shop:good_page' foo.number %}" class="btn btn-primary">商品详情</a><br/>
            ---------------------------------------------------------------------------
            <br/><br/>
        {% endfor %}
    </form>
</body>
</html>

templates/LoginPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    <form action="{% url 'shop:login' %}" method="POST">
        {% csrf_token %}
        {% for foo in form %}
            <p>{{ foo.label }}:{{ foo }}</p>
        {% endfor %}
    <input type="submit" value="登陆"><br/>
    {{ result }}

    </form>
</body>
</html>

templates/MyGoods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的商品</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    <form action="{% url 'shop:my_goods' %}">
        {% for foo in goods %}

            商品名：{{ foo.good.name }}<br/>
            {{ foo.good.image|safe }}<br/>
            价格：￥{{ foo.good.price }}<br/>
            库存：{{ foo.good.amount }}<br/>
            成交额：{{ foo.good.turnover }}<br/>
            状态：{{ foo.situation }}
            <a href="{% url 'shop:put_on' foo.good.number %}" class="btn btn-primary" {{ foo.on_authority }}>
                <input type="button" value="上架">
            </a>
            <a href="{% url 'shop:put_off' foo.good.number %}" class="btn btn-primary" {{ foo.off_authority }}>
                <input type="button" value="下架">
            </a>
            <br/>
            <a href="{% url 'shop:good_page' foo.good.number %}" class="btn btn-primary">商品详情</a><br/>
            <br/>
        {% endfor %}

    </form>
</body>
</html>

templates/NOPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DO NOT</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    <div class="text" style=" text-align:center;"><h1>不要干一些奇奇怪怪的事</h1></div>
    <p style="text-align: center"><img src="/static/img/Laugh.jpg" alt="" width="600" height="600"/></p>
</body>
</html>

templates/RegisterPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="{% url 'shop:register' %}" method="POST">
        {% csrf_token %}
        {% for foo in form %}
            <p>{{ foo.label }}:{{ foo }}</p>
        {% endfor %}
    <input type="submit"><br/>
    {{ result }}



    </form>
</body>
</html>

templates/SearchPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索</title>
</head>
<body>
        <a href="{% url 'shop:welcome' %}">首页</a>
        <a href="{% url 'shop:list' %}" class="btn btn-primary">商品列表</a><br/>
        {% for foo in goods %}
            ---------------------------------------------------------------------------
            <br/>
        商品编码：{{ foo.number }}<br/>
        商品名：{{ foo.name }}<br/>
        价格：￥{{ foo.price }}<br/>
        头像：{{ foo.image|safe }}
        <a href="{% url 'shop:good_page' foo.number %}" class="btn btn-primary">商品详情</a><br/>
            ---------------------------------------------------------------------------
            <br/><br/>
        {% endfor %}
</body>
</html>

templates/SellerList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商家账单</title>
</head>
<body>
    <a href="{% url 'shop:welcome' %}">首页</a><br/>
    ----------------------------------------------------------------------------------------<br/>
    {% for foo in all_list %}
        <form action="{% url 'shop:finish_list' %}" method="POST">
        {% csrf_token %}
        订单号：{{ foo.detail_list.number }}
        <input type="text" value="{{ foo.detail_list.number }}" name="list_number" hidden><br/>
        买家：{{ foo.detail_list.buyer.name }}<br/>
        商品名：{{ foo.good.name }}<br/>
        <a href="{% url 'shop:good_page' foo.good.number %}" class="btn btn-primary">商品详情</a>
        <input type="text" value="{{ foo.good.number }} " name="good_number" hidden><br/>
        {{ foo.good.image|safe }}<br/>
        ￥{{ foo.good.price }} × {{ foo.detail_list.amount }}个 = ￥{{ foo.one_total }}<br/>
        订单状态：{{ foo.list_situation }}
            {% if foo.detail_list.status == 1 %}
                <input type="submit" value="完成"><br/>
            {% endif %}
            <br/>
        </form>
        ----------------------------------------------------------------------------------------<br/>
    {% endfor %}
</body>
</html>

templates/ShopCar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物车</title>
</head>
<body>
<a href="{% url 'shop:welcome' %}">首页</a><br/><h3>{{ no_good }}</h3><br/>
<form action="{% url 'shop:buy' %}" method="POST">
{% csrf_token %}
        {% for foo in car %}
        -----------------------------------------------------------------------------------<br/>
        商品名：{{ foo.good.name }}<br/>
        价格：{{ foo.good.price }}<br/>
        {{ foo.good.image|safe }}<br/>
        <input type="checkbox" value="{{ foo.good.number }}" name="checkbox_list">购买数量：{{ foo.good_amount }}
        <a href="{% url 'shop:car_increase_amount' foo.good.number %}" class="btn btn-primary" name="more">
            <input type="button" value="+" name="more">
        </a>
        <a href="{% url 'shop:car_reduce_amount' foo.good.number %}" class="btn btn-primary" name="less">
            <input type="button" value="-">
        </a>
<br/>
        <a href="{% url 'shop:good_page' foo.good.number %}" class="btn btn-primary">商品详情</a>
        <a href="{% url 'shop:delete_from_car' foo.good.number %}" class="btn btn-primary">
            <input type="button" value="从购物车中删除">
        </a>
        <br/>
        -----------------------------------------------------------------------------------<br/>
    {% endfor %}
    <input type="submit" value="购买" {{ buy_authority }}>
</form>

</body>
</html>

templates/Welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
    <form action="{% url 'shop:welcome' %}" method="POST">
        {{ man }} 你好！
    </form>
    <br/>
    <a href="{% url 'shop:list' %}" class="btn btn-primary">
        商品列表
    </a>
    <br/><br/>
    <a href="{% url 'shop:login' %}" class="btn btn-primary" {{ un_login_authority }}>
        <input type="button" value="登陆">
    </a>
    <br/>
    <a href="{% url 'shop:register' %}" class="btn btn-primary" {{ un_login_authority }}>
        <input type="button" value="注册">
    </a>
    <br/>
    <a href="{% url 'shop:change_password' %}" class="btn btn-primary" {{ login_authority }}>
        <input type="button" value="修改密码">
    </a>
    <br/>
    <a href="{% url 'shop:forget_password' %}" class="btn btn-primary" {{ un_login_authority }}>
        <input type="button" value="忘记密码">
    </a>
    <br/>
    <a href="{% url 'shop:logout' %}" class="btn btn-primary" {{ login_authority }}>
        <input type="button" value="注销">
    </a>


    <br/>
    <br/>
    <a href="{% url 'shop:edit' %}" class="btn btn-primary" {{ seller_authority }}>
        <input type="button" value="编辑新商品">
    </a>
    <br/>
    <a href="{% url 'shop:my_car' %}" class="btn btn-primary" {{ buyer_authority }}>
        <input type="button" value="我的购物车">
    </a>
    <br/>
    <a href="{% url 'shop:my_goods' %}" class="btn btn-primary" {{ seller_authority }}>
        <input type="button" value="我的商品">
    </a>

    <br/>
    <br/>
    <a href="{% url 'shop:buyer_list' %}" class="btn btn-primary" {{ buyer_authority }}>
        <input type="button" value="我的账单">
    </a>
    <br/>
    <a href="{% url 'shop:seller_list' %}" class="btn btn-primary" {{ seller_authority }}>
        <input type="button" value="我的账单">
    </a>



<br/>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js"></script>
    {#    利用jquery来完成form上传等#}
    <script src="http://tinymce.cachefly.net/4.3/tinymce.min.js"></script>
    <script>
        tinymce.init({

            selector: '#my_editor',

            plugins: ["image", "code"],

            file_browser_callback: function (field_name, url, type, win) {

                if (type == 'image') $('#my_form input').click();

            }

        });
    </script>

    <title>商品编辑</title>

</head>

<body>
    {{ result }}<br/><br/>
<form action="{% url 'shop:create_good' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    商品名：<input type="text" name="name" value="{{ name }}"><br/>
    价格：<input type="text" name="price" value="{{ price }}"><br/>
    库存：<input type="text" name="amount" value="{{ amount }}"><br/>
    商品头像：<input type="file" name="img" value="{{ img }}"><br/>
    介绍：
    <textarea id="my_editor" rows="25" name="description"></textarea>
    <br/>{{ form.lable }}{{ form }}<br/>

    <input type="submit">
</form>

<iframe id="form_target" name="form_target" style="display:none"></iframe>

<form id="my_form" action="{% url 'shop:upload_img' %}" target="form_target" method="post" enctype="multipart/form-data"
      style="width:0px;height:0;overflow:hidden">
    <input name="image" type="file" onchange="$('#my_form').submit();this.value='';">
</form>

</body>

</html>